// <auto-generated />
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SampleDotNet.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SampleDotNet.Database.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Uzumaki Naruto",
                            Password = "$2a$11$cP05Yeo9CTkJn8K.KRCgs.LRFxkD3dh0cmh2ebBYp.TvAfpYjGeMS",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hayate Kakashi",
                            Password = "$2a$11$cP05Yeo9CTkJn8K.KRCgs.LRFxkD3dh0cmh2ebBYp.TvAfpYjGeMS",
                            Username = "user1"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Uchiha Madara",
                            Password = "$2a$11$cP05Yeo9CTkJn8K.KRCgs.LRFxkD3dh0cmh2ebBYp.TvAfpYjGeMS",
                            Username = "user1"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
